server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    datasource:
      url: jdbc:mysql://localhost:3306/travel_24_12?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
api:
  public-data-key: #
  openweather-key: #
  kakao-map-key: #